config/routes.rb
Rails.application.routes.draw do
  
  resources :search_suggestions
  root 'bottles#index'
  get '/impressum' => 'bottles#impressum'
  get '/kontakt' => 'bottles#kontakt'
  get '/servicebedingung' => 'bottles#servicebedingungen'
  get '/datenschutz' => 'bottles#datenschutz'
  get "bottles/update_text", as: "update_text"
    get "bottles/update_category", as: "update_category"
  resources :searches
  resources :bottles

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
  
    belongs_to :shop, dependent: :destroy
    
    
    def self.calculate_price(flaschen, quantity)
        preis_array = []
        flaschen.each do |x|
            x.inhalt =  "n/a" if x.inhalt.blank? 
            x.price_per_litre_string =  "n/a" if x.price_per_litre_string.blank? 
            x.price =  "n/a" if x.price.blank? 
            preis = x.price * quantity.to_i
            preis_array << preis
           
        end
        return preis_array
    end
    
    
    def self.search_wines(search, category,country, grape)
   # where('LOWER(name) LIKE :search', search: "%#{search}%")
    #Bottle.where(["lower(name) LIKE lower(?)", name2]) if name2.present?
   #bottle = bottle.where(["category LIKE ?", category]) if category.present?
     bottle = Bottle.all
    if search != ""
    bottle = bottle.where(["name LIKE ?", "%#{search}%"]) if search.present?
    bottle = bottle.where(["category LIKE ?", category]) if category.present? and category != "Alle Kategorien"
    bottle = bottle.where(["country LIKE ?", country]) if country.present? and country != "Alle Länder"
    bottle = bottle.where(["grape LIKE ?", grape]) if grape.present? and grape != "Alle Rebsorten"
    else
    bottle = bottle.where(["category LIKE ?", category]) if category.present? and category != "Alle Kategorien"
    bottle = bottle.where(["country LIKE ?", country]) if country.present? and country != "Alle Länder"
    bottle = bottle.where(["grape LIKE ?", grape]) if grape.present? and grape != "Alle Rebsorten"
    end
    return bottle
    
    
    
    end
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
    
 

    
   def update_text
           @country_value == "Alle Länder"
       if params[:category_name] != "Alle Kategorien" and (params[:country_name] == "Alle Länder")
           @rebsorten = Bottle.where(category: params[:category_name] ).pluck(:grape).uniq
           @rebsorten.sort_by!{ |e| e.downcase }
           @rebsorten.unshift("Alle Rebsorten")
       elsif (params[:category_name] == "Alle Kategorien") and (params[:country_name] != "Alle Länder")
           @rebsorten = Bottle.where(country: params[:country_name] ).pluck(:grape).uniq
           @rebsorten.sort_by!{ |e| e.downcase }
           @rebsorten.unshift("Alle Rebsorten")
       elsif (params[:category_name] == "Alle Kategorien") and (params[:country_name] == "Alle Länder")
           @rebsorten = Bottle.order(:grape).pluck(:grape).uniq
           @rebsorten.sort_by!{ |e| e.downcase }
           @rebsorten.unshift("Alle Rebsorten")
        elsif (params[:category_name] != "Alle Kategorien")
           @rebsorten = Bottle.where(category: params[:category_name]).pluck(:grape).uniq
           @rebsorten.sort_by!{ |e| e.downcase }
           @rebsorten.unshift("Alle Rebsorten")
       else
           @rebsorten = Bottle.where(country: params[:country_name], category: params[:category_name]).pluck(:grape).uniq
           @rebsorten.sort_by!{ |e| e.downcase }
           @rebsorten.unshift("Alle Rebsorten")
       end
   end
 
  def update_category
      
     if   (params[:category_name] != "Alle Kategorien") and (params[:country_name] != "Alle Länder")
          @country = Bottle.where(category: params[:category_name]).pluck(:country).uniq
          @country.sort_by!{ |e| e.downcase }
          @country.unshift("Alle Länder")
          @grape = Bottle.where( category: params[:category_name]).pluck(:grape).uniq
          @grape.sort_by!{ |e| e.downcase }
          @grape.unshift("Alle Rebsorten")
      elsif (params[:category_name] == "Alle Kategorien") and (params[:country_name] == "Alle Länder")
          @country = Bottle.order(:country).pluck(:country).uniq
          @country.sort_by!{ |e| e.downcase }
          @country.unshift("Alle Länder")
          @grape = Bottle.order(:grape).pluck(:grape).uniq
          @grape.sort_by!{ |e| e.downcase }
          @grape.unshift("Alle Rebsorten")
          
     elsif (params[:category_name] != "Alle Kategorien") and (params[:country_name] == "Alle Länder") 
          @country = Bottle.where(category: params[:category_name]).pluck(:country).uniq
          @country.sort_by!{ |e| e.downcase }
          @country.unshift("Alle Länder")
          @grape = Bottle.where(category: params[:category_name]).pluck(:grape).uniq
          @grape.sort_by!{ |e| e.downcase }
          @grape.unshift("Alle Rebsorten")
     elsif (params[:category_name] == "Alle Kategorien" and params[:country_name] != "Alle Länder")
        @country = Bottle.order(:country).pluck(:country).uniq
        @grape = Bottle.where(grape: params[:country_name]).pluck(:grape).uniq
        @grape.sort_by!{ |e| e.downcase }
        @grape.unshift("Alle Rebsorten")
     else
        @country = Bottle.where(category: category_name).pluck(:country).uniq 
        @country.sort_by!{ |e| e.downcase }
        @country.unshift("Alle Länder")
        @grape = Bottle.where(category: category_name).pluck(:grape).uniq
        @grape.sort_by!{ |e| e.downcase }
        @grape.unshift("Alle Rebsorten")
          
          
      end
  end 
         
    def index   
        
        @filterProducts = true
        
        
        
        
        
        @all_flasch = Bottle.order(:name)
        
        liste_namen = []
        @alle_flaschen = Bottle.all
        @alle_flaschen.each do |x|
            liste_namen << x.name
        end
        
        hash = Hash[@alle_flaschen.map { |l| [l.name] }]
        data=  @alle_flaschen.map(&:name)
        @data = data.to_json
        
        @liste_der_weine = liste_namen
       #     <%= text_field_tag :search, params[:search],  class:"form-control", placeholder: "Suchen", data: {autocomplete_source: @data} %>
        # @categories = Bottle.uniq.pluck(:category) 
        # @grape = Bottle.uniq.pluck(:grape)
        # @country = Bottle.uniq.pluck(:country) 
         
      
   # @flaschen = Bottle.search_wines(params[:search],params[:category], params[:grape])
    grape = params[:grape]
    category = params[:category]
    country = params[:country]
    search = params[:search]
    
    @flaschen = Bottle.search_wines(search,category,country,grape).order(price: :ASC).page(params[:page]).per(20)
  
    
    
    
 #   if grape != "Alle Rebsorten"
 #    @flaschen = Bottle.where(["lower(name) LIKE lower(?) AND category LIKE ? AND country LIKE ? AND grape LIKE ?","%#{params[:search]}%","%#{params[:category]}%","%#{params[:country]}%","%#{grape}%"]).order(price: :ASC).page(params[:page]).per(20)
 #   else 
 #   @flaschen = Bottle.where(["lower(name) LIKE lower(?) AND category LIKE ? AND country LIKE ?","%#{params[:search]}%","%#{params[:category]}%","%#{params[:country]}%"]).order(price: :ASC).page(params[:page]).per(20)
 #   # @flaschen = Bottle.search_wines(params[:search])
 #   end
 #    @flaschen = @flaschen.order(price: :ASC).page(params[:page]).per(20)
 #    
 #    
 #    
 #   
 #  
 #        
 #    
 #      
 #      
 #       params[:quantity] = 1   if params[:quantity].blank?
 #       @final_price = Bottle.calculate_price(@flaschen, params[:quantity])        
 #      
 #      @big_array = @flaschen.zip(@final_price)
    end
    
    def impressum
    end
    
    def kontakt
    end
    
    def servicebedingungen
    end
    
    
    def datenschutz
    end
    
    def create
        @auswahl = params[:category]
    end
    
    
   
    
        
    
    
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/views/bottles/index.html.erb
<div class="slider">
<div class="overlay">
<div class="head-text">
    
  
  <div class="text-center">
    <h2>Wein dort kaufen, wo er am günstigsten ist</h2>
    <p class="lead">Vergleiche das Angebot von über 80 Shops mit mehr als 9000 Weinen</p>
  </div>
  
</div><!-- /.container -->

 

       
    
    <div class="jumbotron">
        
<!--        <video loop autoplay muted poster="#" id="bgvid" playsinline autoplay muted>-->
  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->
<!--<source src="http://media.istockphoto.com/videos/choosing-wine-video-id519351126" type="video/mp4">-->
<!--</video>-->
    <div class="container">
        
        
        
        <div class="search">
        <h1>Wein Günstig Kaufen</h1>
     <div class="formwrapper">
              <%= form_tag root_path, :method => 'get' do %>
              <div class="input-group">
                     
                     <%= text_field_tag :search, params[:search],  class:"form-control", placeholder: "Suchen", data: {autocomplete_source: @data} %>
                      <span class="input-group-btn"><%= submit_tag "Suchen", class: "btn btn-primary" %></span>
      
       <script>
  var src =  $('#search').data('autocomplete-source')
  $( function() {
    
    $( "#search" ).autocomplete({
      
      source: function(request, response) {
        var results = $.ui.autocomplete.filter(src, request.term);
        
        response(results.slice(0, 10));
    }
    });
  } );
  
  
 
  </script>

<script>
 $(document).ready(function() {
     $("select").prop("selectedIndex",0);
    $('#clear').click(function() {
      $("select").prop("selectedIndex",0);
    });
  });
        

</script>
 
        

        
        
              </div>
     </div>
    <div class="controls">
     
<%= form_tag("filter", :id => "filter_form", :method => "post") do %>
<label for="kategorie" class="kategorie">Kategorie:</label> <%=  select_tag :category,
      options_for_select(Bottle.pluck(:category).uniq.sort_by!{ |e| e.downcase }, params[:category]),
      { include_blank: 'Alle Kategorien' }%>
  <label for="country" class="country">Herkunft:</label> <%=  select_tag :country,
      options_for_select(Bottle.pluck(:country).uniq.sort_by!{ |e| e.downcase }, params[:country]),
      { include_blank: 'Alle Länder' }%>
  <label for="grape" class="grape">Rebsorte:</label> <%=  select_tag :grape,
      options_for_select(Bottle.pluck(:grape).uniq.sort_by!{ |e| e.downcase }, params[:grape]),
      { include_blank: "Alle Rebsorten" }%>

  
 <script>
  $(document).ready(function() {
    $('#country').change(function() {
        var category_na = $("#category option:selected").text();
        $.ajax({
           url: "<%= update_text_path %>",
           data: {
               country_name: $("#country option:selected").text(), category_name: category_na
           },
           dataType: "script"
        });
        
        
       
    });
    
    
    
    $('#category').change(function() {
        var country_name  = $("#country option:selected").text();
        $.ajax({
           url: "<%= update_category_path %>",
           data: {
               category_name: $("#category option:selected").text(), country_name: country_name
           },
           dataType: "script"
        });
    });
  });
</script>   
        
       <!-- <label for="quantity">Menge</label> -->
        <% #select_tag :quantity, options_for_select(1..50, params[:quantity]) %>
        <%= form_tag root_path, :method => 'get' do %>
       <div class="btn btn-primary btn-xs", id="clear">Zurücksetzen</div> 
        <% end %>
        <% end %>
<% end %>
    </div>
    <div class="pages">
     <ul class="pagination">
                <%= paginate @flaschen ,:window => 2 %>
          </ul>
     </div>
    </div>
   </div>
    </div>
</div>
</div>
    
    
<% if @flaschen.empty? %>
<div class="search-field">
    <div class="nothing-found">
       <span><p>Ihre Suche nach "<%=params[:search]%>" führte leider zu keinem Ergebnis </p></span> 
    </div>
</div>

<% else %>
    <div class="search-field">
         <% @flaschen.each do |products| %>
                <a href=<%= products.product_url %>>
                    <%end%>
    
    
                 <% @flaschen.each_slice(6) do |products| %>
                    <div class="row">
                          <% products.each do |product| %>
                        <div>
                            <a href=<%= product.product_url %> title="<%= product.name %>">
                        <div class="col-lg-2 col-sm-4 col-xs-6 col-md-4">
                            <div class="thumbnail">
                                <%= image_tag(product.image_url, class: 'list_image', size: '160x220', alt: product.name) %>
                                <div class="logo-div"><%= image_tag(Shop.find(product.shop_id).shop_logo, class: 'shop-logo', size: '160x220', alt: 'shop logo') %></div>
                                <div class="caption">
                                 <!--<h4 class="pull-right">$24.99</h4>-->
                                   <div class="product-name"><p> <%= product.name %></p></a></div>
                                   <div class="price"><p><%= '%.2f' % product.price  %>€</p></div>
                                   <div class="price-calculation"><p>
                                       
                                <%-# Berechnung vom Gesamtpreis -%>
                                   <% 
                                   
                                    bottle = Shop.find(product.shop_id)
                                    menge = params[:quantity]
                                    menge = menge.to_i
                                    versandkosten = bottle.versandkosten
                                    if menge != nil
                                        first_price = menge * product.price
                                        if bottle.mengenrabatt != nil
                                           if menge >= bottle.mengenrabatt_menge 
                                               calc_mengenrabatt = first_price * bottle.mengenrabatt
                                           else
                                            calc_mengenrabatt = 0
                                           end
                                        else
                                            calc_mengenrabatt = 0 
                                        end
                                        if bottle.verpackungsrabatt_menge != nil 
                                            if menge >=  bottle.verpackungsrabatt_menge 
                                                calc_verpackungsrabatt = first_price * bottle.verpackungsrabatt
                                            else
                                            calc_verpackungsrabatt = 0
                                            end
                                            
                                        else
                                            calc_verpackungsrabatt = 0
                                        end
                                        
                                        if bottle.versandkostenfrei_ab_betrag != nil and !bottle.versandkosten.nil? and !bottle.versandkostenfrei_ab_betrag.nil?
                                           if  first_price > bottle.versandkostenfrei_ab_betrag 
                                               versandkosten = 0
                                           end
                                        else
                                            versandkosten = bottle.versandkosten
                                        end
                                        if versandkosten.nil?
                                            versandkosten = 0
                                        end
                                        fin_preis = first_price + versandkosten #- calc_mengenrabatt#- #calc_verpackungsrabatt
                                    end%>

                                <% if params[:quantity] != 0 %>
                                 <table style="width:100%">
                                              <tr>
                                                <th>Information</th>
                                                <th></th>
                                              </tr>
                                              <tr>
                                                <td>Jahrgang:</td>
                                                <%if product.vintage != nil%>
                                                <td><%= product.vintage %></td>
                                                <%else%>
                                                <td>N/A</td>
                                                <%end%>

                                              </tr>
                                               <tr>
                                                <td>Rebsorte:</td>
                                                <%if product.grape != nil%>
                                                <td><%= product.grape %></td>
                                                <%else%>
                                                <td>N/A</td>
                                                <%end%>

                                              </tr>
                                              <tr>
                                                <td>Land:</td>
                                                <%if product.country != nil%>
                                                <td><%= product.country %></td>
                                                <%else%>
                                                <td>N/A</td>
                                                <%end%>

                                              </tr>
                                              <tr>
                                                <td>Inhalt:</td>
                                                
                                                <% if !product.inhalt.nil?
                                                product.inhalt.gsub("Flaschen", "") 
                                                end%>
                                                <td><%= product.inhalt %></td>
                                              </tr>
                                              <tr>
                                                <td>€/L:</td>
                                                 <% if !product.price_per_litre_string.nil? %>
                                                <%product.price_per_litre_string.gsub!("/", "") %>
                                                <%product.price_per_litre_string.gsub!("L", "") %>
                                                <%product.price_per_litre_string.gsub!("EUR", "") %>
                                                <%product.price_per_litre_string.gsub!("€", "") %>
                                                <%product.price_per_litre_string.gsub!("1l", "") %>
                                                 <%end%>
                                                <td><%= product.price_per_litre_string %>€</td>
                                              </tr>
                                            </table> 
                                
                                
                                   <!-- <div><p>Menge: 
                                    <%#params[:quantity]%></p></div>
                                    <div><p>Versandkosten: <%#'%.2f' %versandkosten%>€</p></div>
                                    <div><p>Gesamtpreis: <%#'%.2f' % fin_preis%>€</p></div> -->
                                        
                                <%end%></p></div>
                                    
                                   
                                    
                                    
                                </div>
                               </div>
                            </div>
                        </div>
        <%end%>
                      </div>
                        <%end%>
                    </div>
<%end%>

app/views/bottles/kontakt.html.erb
<head><link rel="stylesheet" type="text/css" href="impressum.css"></head>

<div class="head-section">
 <div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Wein-günstig-kaufen.com", root_path, class:"navbar-brand" %>
    </div>
      <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Zurück", root_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
</div>

<div class="wrapper">
<div class="infosite">
<div
class="container"><div
class="std"><p>Aaron Tal<br
/>Kollenhof 22<br
/>22527 Hamburg</p><p>Telefon:&nbsp;+49 162 2886035</p><p>E-Mail: <a
href="mailto:aaron.tal@hotmail.de">aaron.tal@hotmail.de</a></p>
</div>
</div>
</div>

<div class="push"></div>
</div>

app/views/bottles/update_category.js.erb
$('#country').html("<%= escape_javascript options_for_select(@country)%>");
$('#grape').html("<%= escape_javascript options_for_select(@grape)%>");
$("#country").prop("selectedIndex",0);

app/views/bottles/update_text.js.erb
$('#grape').html("<%= escape_javascript options_for_select(@rebsorten)%>");