config/routes.rb
Rails.application.routes.draw do
  
  resources :search_suggestions
  root 'bottles#index'
  get '/impressum' => 'bottles#impressum'
  get '/kontakt' => 'bottles#kontakt'
  get '/servicebedingung' => 'bottles#servicebedingungen'
  get '/datenschutz' => 'bottles#datenschutz'
  get "bottles/update_text", as: "update_text"
    get "bottles/update_category", as: "update_category"
  resources :searches
  resources :bottles

end

app/models/search.rb
class Search < ActiveRecord::Base

def search_wines
    
    bottle = Bottle.all
    
    bottle = bottle.where(["name LIKE ?", "%#{keywords}%"]) if keywords.present?
    bottle = bottle.where(["category LIKE ?", category]) if category.present?
    bottle = bottle.where(["price >= ?", min_price]) if min_price.present?
    bottle = bottle.where(["price <= ?", max_price]) if max_price.present?
    bottle = bottle.where(["vintage LIKE ?", vintage]) if vintage.present?
    
    
    return bottle
end

    
    
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    
    def new 
        @search = Search.new
        @categories = Bottle.uniq.pluck(:category)
    end
    
    def create
        @search = Search.create(search_params)
        redirect_to @search
    end
    
    def show
        @search = Search.find(params[:id])
        
    end
    
    private
    
    def search_params
        params.require(:search).permit(:keywords, :category, :min_price, :max_price, :vintage)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<%= form_for @search, html: {class:"pure-form"} do |s| %>


<div class="field">
    <%= s.label :keywords %><br/>
     <%= s.text_field :keywords %>
</div>

<div class="field">
    <%= s.label :category %><br/>
     <%= s.select :category, options_for_select(@categories), :include_blank => true %>
</div>

<div class="field">
    <p><%= s.label :min_price, "Minimum Preis" %> - <%= s.text_field :min_price, size:10 %></p>
    <p><%= s.label :max_price, "Maximum Preis" %> - <%= s.text_field :max_price, size:10 %></p>
    
</div>

<div class="field">
    <p><%= s.label :vintage, "Jahrgang" %> - <%= s.text_field :vintage, size:10 %></p>
    
</div>

<div class="actions">
    <p><%= s.submit "Suchen", class: "pure-button pure-button-primary" %>
</div>

<p><%= link_to "Zurück", root_path %></p>
<%end %>

app/views/searches/show.html.erb
<h1>Suchergebnisse</h1>
<p><%= link_to "Zurück", new_search_path %></p>

<% if @search.search_wines.empty? %>
<p>Keine Ergebnisse gefunden</p>

<% else %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Vintage</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @search.search_wines.each do |wein| %>
    
    <tr>
        <td><%= wein.name %></td>
        <td><%= image_tag(wein.image_url, :alt => wein.image_url, :class => "img_preview") %></td>
        <td><%= image_tag(wein.shop.shop_logo, :alt => "shop-logo", :class => "img_preview") %></td>
        <td><%= "%.2f" % wein.price  %></td>
        <td><%= wein.vintage %></td>
        <td><%= link_to "Zum Shop", wein.product_url %></td>
    <tr>
   
    
  
    
<% end %>
</tbody>
  </table>
<br>
<% end %>