config/routes.rb
Rails.application.routes.draw do
  
  resources :search_suggestions
  root 'bottles#index'
  get '/impressum' => 'bottles#impressum'
  get '/kontakt' => 'bottles#kontakt'
  get '/servicebedingung' => 'bottles#servicebedingungen'
  get '/datenschutz' => 'bottles#datenschutz'
  get "bottles/update_text", as: "update_text"
    get "bottles/update_category", as: "update_category"
  resources :searches
  resources :bottles

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>wein-günstig-kaufen.com</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="google-site-verification" content="AyPtOIE3Zv-_EVatg3rut8JUuV4HqZ902jsG-ATJrL0" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-85416502-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

    <div class="box">
<body>

<%= yield %>

</body>


<footer class="footer1">
      <div class="container">
     <%= link_to " Impressum |", impressum_path %>
     <%= link_to " Kontakt |", kontakt_path %>
     <%= link_to " Servicebedingung | ", servicebedingung_path %>
     <%= link_to " Datenschutz ", datenschutz_path %>  
      </div>
    </footer>

</div>
</html>

app/views/layouts/infosite.html.erb
<html>
    <head>
        <%= stylesheet_link_tag "impressum" %>
    </head>
    <body>
        <%= yield %>
        
</body>
  <footer class="footer1">
      <div class="container">
         <%= link_to " Impressum |", impressum_path %>
         <%= link_to " Kontakt ", kontakt_path %>
      </div>
    </footer>

</html>